FROM node:10.16.0
WORKDIR /cc
COPY . /cc
ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN npm install pm2 -g
EXPOSE 8042
CMD ["pm2-runtime", "app.js"]